### ISSUE TITLE
Question: How to deploy on CoreOS?

### ISSUE THREAD

**Issue by tobilg** [contiv/volplugin#103]
Are there any hints on how to run the `volplugin` on CoreOS?

We run a fully Dockerized Mesos and Ceph environment, and for using stateful containers, we'd like to use Docker volumes on Ceph. As far as I understand the installation of this plugin requires the some libraries to be present on the host system.

As CoreOS works a little different then CentOS/Debian/etc., is there a way to run the plugin within a container itself? If no, how would I otherwise be able to use it on CoreOS?

**Comment by erikh** [comment]
It should be possible, but we're not testing it currently. A few other people have attempted this and this is being (loosely) tracked here: https://github.com/contiv/volplugin/issues/66.

See https://github.com/contiv/volplugin/issues/102 for specific problems related to CoreOS right now. I am going to raise the issue with the CoreOS folks and see if I can get some better answers as to why the `rbd` tool is not available in the host environment, which we depend on for most of our ceph-related operations.

I'm currently vacationing and will be available to answer questions, but I can't really do much development ATM. I return at the end of January.

I'll review this once I get back and see if I can come up with a good set of parameters for you to try out.

**Comment by tobilg** [comment]
Thanks for the fast reply, and have a nice vacation!

**Comment by philips** [comment]
@erikh I think a good way to do this would be to use the [rkt fly stage1](https://github.com/coreos/rkt/blob/6a60ca625371dd0abb0228e013edec8d5e5465b4/Documentation/running-fly-stage1.md). Then you can include rbd, volplugin, etc inside of a container and run it as a container.

**Comment by philips** [comment]
cc @steveeJ @jonboulle

**Comment by erikh** [comment]
@philips OK, I will try that when I get back!

**Comment by erikh** [comment]
Thanks!

**Comment by jonboulle** [comment]
Please ping us on rkt-dev or the GH repo to let us know how you go.

**Comment by erikh** [comment]
@jonboulle will do -- still here for another week, and I plan to get to this as soon as time permits when I get back -- top priority.

**Comment by h0tbird** [comment]
I did some research on this topic and I ended up creating this project https://github.com/h0tbird/docker-volume-rbd. I did some attempts with `rkt` but at that time `fly` was not available so I used `systemd-nspawn`. Whenever `rkt fly` hits alpha I will try it.

**Comment by tobilg** [comment]
@h0tbird Thanks a lot for your comment. I looked at the project, and saw that you're using the `h0tbird/ceph:v9.2.0-2` image. Would it also be possible to use official `ceph/daemon` image?

**Comment by h0tbird** [comment]
@tobilg Yes `h0tbird/ceph` is just a wrapper around `ceph/daemon` with a patched `/usr/sbin/ceph-disk` I had the need to fix 2 [bugs](https://github.com/h0tbird/docker-ceph/releases/tag/v9.2.0-2) and to lock my container version to `v9.2.0-2`.

**Comment by tobilg** [comment]
I forked [h0tbird/docker-volume-rbd](https://github.com/h0tbird/docker-volume-rbd) and updated the driver imports for `volume` to [docker/go-plugins-helpers/volume](github.com/docker/go-plugins-helpers/volume) as [calavera/dkvolume](https://github.com/calavera/dkvolume) is outdated.

I also added an `install.sh` script which will compile the driver and put it in `/opt/bin`, and created a `systemd` unit for the plugin.

Works nicely for me in our CoreOS cluster. You can have a look at [tobilg/docker-volume-rbd](https://github.com/tobilg/docker-volume-rbd) if you like. This is a quick hack and I'm a beginner, so please bare with me for my code :-)

**Comment by erikh** [comment]
@tobilg @h0tbird I believe I have an answer for you now (I got back from China yesterday), hopefully you will find it useful.

```
docker run --pid host --net host -v /var/lib/ceph:/var/lib/ceph -v /etc/ceph:/etc/ceph -v /var/run/ceph:/r/run/ceph -v /sys:/sys --privileged -v /dev:/dev -v /run/docker/plugins:/run/docker/plugins contiv/volplugin volplugin --debug
```

Will run `volplugin --debug`. It is backed by @h0tbird's `ceph/rbd` image (and therefore requires the permissions it needs to map volumes).

Note there is more to setting up volplugin than that such as etcd, volmaster, and volsupervisor. The vol* binaries plus the CLI tool (volcli) are included in the image, so you can do it all in containers if you want now. :)

Please read the docs we have over at http://docs.contiv.io so you can get familiar with the tool arguments. The build is today's master.

If you guys have time to try this out, I would appreciate it!

**Comment by erikh** [comment]
#66 covers this, I see no point in leaving this open
