### ISSUE TITLE
Re-upload of policy orphans volumes

### ISSUE THREAD

**Issue by erikh** [contiv/volplugin#181]
reproduction:

```
volcli policy upload policy1 < /testdata/intent1.json
volcli volume create policy1/test
volcli policy upload policy1 < /testdata/fastsnap.json
volcli volume create policy1/test2
volcli volume list-all
<output>
policy1/test2
</output>
```

The resulting `policy1/test` is still in existence, but its etcd record is gone, basically orphaning it.

This should be an easy patch so I would ask that some others on the team could take it?

**Comment by mapuri** [comment]
@erikh I can look into this. I am assuming the correct behavior would be to fail the second upload if policy with that name already exists, right?

**Comment by mapuri** [comment]
ah, nvm I think I got it wrong. This is the case where user wants to update the intent so the volumes with old intent should have continued to exist.

**Comment by erikh** [comment]
Correct on the last post; we re-upload the policy without trashing the volumes.
