### ISSUE TITLE
volcli improvement: detect etcd missing keys and respond with nicer messages

### ISSUE THREAD

**Issue by erikh** [contiv/volplugin#182]
Currently this would involve changes to the volmaster, config library and volcli. If the volmaster was smart enough to return 404 on etcd "key not found" failures, it would be a much nicer user experience, and easier to test in the long term I think. It could also exit a different value if the etcd key is missing.

**Comment by erikh** [comment]
@dseevr can you take this one?

**Comment by dseevr** [comment]
Yep, I'll just need to be pointed to the relevant code sections, and I probably won't have time to start looking at it until the weekend.
