### ISSUE TITLE
having issue running make run-build

### ISSUE THREAD

**Issue by rmartinez3** [contiv/volplugin#201]
make run-build
go get -u github.com/kr/godep
GOGC=1000 godep go install -v ./volcli/volcli/ ./volplugin/volplugin/ ./volmaster/volmaster/ ./volsupervisor/volsupervisor/
config/global.go:12:2: cannot find package "github.com/Sirupsen/logrus" in any of:
	/usr/lib/golang/src/github.com/Sirupsen/logrus (from $GOROOT)
	/home/rodrigo/newwork/src/github.com/contiv/volplugin/Godeps/_workspace/src/github.com/Sirupsen/logrus (from $GOPATH)
	/home/rodrigo/newwork/src/github.com/Sirupsen/logrus
config/volume.go:13:2: cannot find package "github.com/alecthomas/units" in any of:
	/usr/lib/golang/src/github.com/alecthomas/units (from $GOROOT)
	/home/rodrigo/newwork/src/github.com/contiv/volplugin/Godeps/_workspace/src/github.com/alecthomas/units (from $GOPATH)
	/home/rodrigo/newwork/src/github.com/alecthomas/units
volcli/volcli/cli.go:7:2: cannot find package "github.com/codegangsta/cli" in any of:
	/usr/lib/golang/src/github.com/codegangsta/cli (from $GOROOT)
	/home/rodrigo/newwork/src/github.com/contiv/volplugin/Godeps/_workspace/src/github.com/codegangsta/cli (from $GOPATH)
	/home/rodrigo/newwork/src/github.com/codegangsta/cli
volcli/volcli.go:18:2: cannot find package "github.com/contiv/errored" in any of:
	/usr/lib/golang/src/github.com/contiv/errored (from $GOROOT)
	/home/rodrigo/newwork/src/github.com/contiv/volplugin/Godeps/_workspace/src/github.com/contiv/errored (from $GOPATH)
	/home/rodrigo/newwork/src/github.com/contiv/errored
storage/backend/ceph/ceph.go:16:2: cannot find package "github.com/contiv/executor" in any of:
	/usr/lib/golang/src/github.com/contiv/executor (from $GOROOT)
	/home/rodrigo/newwork/src/github.com/contiv/volplugin/Godeps/_workspace/src/github.com/contiv/executor (from $GOPATH)
	/home/rodrigo/newwork/src/github.com/contiv/executor
watch/watch.go:11:2: cannot find package "github.com/coreos/etcd/client" in any of:
	/usr/lib/golang/src/github.com/coreos/etcd/client (from $GOROOT)
	/home/rodrigo/newwork/src/github.com/contiv/volplugin/Godeps/_workspace/src/github.com/coreos/etcd/client (from $GOPATH)
	/home/rodrigo/newwork/src/github.com/coreos/etcd/client
volcli/volcli.go:21:2: cannot find package "github.com/kr/pty" in any of:
	/usr/lib/golang/src/github.com/kr/pty (from $GOROOT)
	/home/rodrigo/newwork/src/github.com/contiv/volplugin/Godeps/_workspace/src/github.com/kr/pty (from $GOPATH)
	/home/rodrigo/newwork/src/github.com/kr/pty
watch/watch.go:12:2: cannot find package "golang.org/x/net/context" in any of:
	/usr/lib/golang/src/golang.org/x/net/context (from $GOROOT)
	/home/rodrigo/newwork/src/github.com/contiv/volplugin/Godeps/_workspace/src/golang.org/x/net/context (from $GOPATH)
	/home/rodrigo/newwork/src/golang.org/x/net/context
storage/backend/ceph/ceph.go:13:2: cannot find package "golang.org/x/sys/unix" in any of:
	/usr/lib/golang/src/golang.org/x/sys/unix (from $GOROOT)
	/home/rodrigo/newwork/src/github.com/contiv/volplugin/Godeps/_workspace/src/golang.org/x/sys/unix (from $GOPATH)
	/home/rodrigo/newwork/src/golang.org/x/sys/unix
volplugin/handlers.go:15:2: cannot find package "github.com/docker/docker/pkg/plugins" in any of:
	/usr/lib/golang/src/github.com/docker/docker/pkg/plugins (from $GOROOT)
	/home/rodrigo/newwork/src/github.com/contiv/volplugin/Godeps/_workspace/src/github.com/docker/docker/pkg/plugins (from $GOPATH)
	/home/rodrigo/newwork/src/github.com/docker/docker/pkg/plugins
volplugin/volplugin.go:21:2: cannot find package "github.com/gorilla/mux" in any of:
	/usr/lib/golang/src/github.com/gorilla/mux (from $GOROOT)
	/home/rodrigo/newwork/src/github.com/contiv/volplugin/Godeps/_workspace/src/github.com/gorilla/mux (from $GOPATH)
	/home/rodrigo/newwork/src/github.com/gorilla/mux
godep: go exit status 1
make: *** [run-build] Error 1

**Comment by erikh** [comment]
Hi! Try upgrading your go to go 1.6 and see what happens, if you don't 
mind.

-Erik

**Comment by rmartinez3** [comment]
Yea had version 1.5 upgrading it to 1.6 got it to work. It was able to get the go dependencies. Thanks for the help. 

So if you have go version lower than 1.6  you wont be able to build because the godep,json is set to version 1.6??

**Comment by erikh** [comment]
go 1.6 turns on a feature which we want, that eliminates the need for godep as a wrapper; you can just use the vendor/ directory now instead of doing what godep needed to do before.

I haven't quite gutted all the godep code yet because I was hoping it'd still work for 1.5, but that's apparently not the case.

Let me know if you run into any more problems; gonna close this one.
