### ISSUE TITLE
latest volcli breaks contivctl

### ISSUE THREAD

**Issue by erikh** [contiv/volplugin#210]
Reference: http://contiv.ngrok.io/job/Contivctl_Release/25/

**Comment by erikh** [comment]
This is the crux of the issue:

```
./main.go:26: cannot use volcli.GlobalFlags (type []"github.com/contiv/contivctl/vendor/github.com/contiv/volplugin/vendor/github.com/codegangsta/cli".Flag) as type []"github.com/codegangsta/cli".Flag in field value
./main.go:27: cannot use volcli.Commands (type []"github.com/contiv/contivctl/vendor/github.com/contiv/volplugin/vendor/github.com/codegangsta/cli".Command) as type []"github.com/codegangsta/cli".Command in field value
```

Unfortunately this means that we have to think of a new strategy for embedding the tools. I think turning contivctl into a shell script which netctl and volcli can use depending on which command set is requested is the simplest thing that could possibly work.

WDYT @shaleman @mapuri?

**Comment by mapuri** [comment]
@erikh 

Yes, I think a shell script will work. 

To make sure I understand the issue, compilation failure is showing up as these types (`...codegangsta/cli".Flag` and `...codegangsta/cli".Command`) differ between the latest version of `codegansat/cli` (that contivctl is pulling) and the version that the projects are using?

We could solve it by bumping up the godeps in our projects (volcli and netctl) as well, right? 

Just to share my thinking, I am not sure how much folks are keen on actively maintaining contivctl, as we still use per-project command-line utilities in customer demo setups and even our readme files. But at the same time having contivctl gives a very good unified preview of all things under the ContivProject.

contivctl in it's current form needs minimal maintenance (other than these occasional failures), which is a big plus. If adding more plumbing and code would add to this maintenance we will need to make sure we are ready to dedicate some energy to that.

/cc @jainvipin as well.

**Comment by erikh** [comment]
no, it's because the paths differ; I'm fairly certain they're using the same version.

I'll move forward with the shell script today.

**Comment by erikh** [comment]
to answer the longer question (which I missed at first); I think the end-user will want this tool, and if not, we can provide the script for those who do. I don't think it'll be very complicated.

**Comment by mapuri** [comment]
sgtm @erikh 

> it's because the paths differ; I'm fairly certain they're using the same version

from the original failure, it did look like it was a version issue. For instance, the `cli.Flag` implementation is different between [the latest](https://github.com/codegangsta/cli/blob/master/flag.go#L35) and [volplugin's vendored](https://github.com/contiv/volplugin/blob/master/vendor/github.com/codegangsta/cli/flag.go#L34) version of `codegangsta/cli`.

```
./main.go:26: cannot use volcli.GlobalFlags (type []"github.com/contiv/volplugin/vendor/github.com/codegangsta/cli".Flag) as type []"github.com/codegangsta/cli".Flag in field value
./main.go:27: cannot use volcli.Commands (type []"github.com/contiv/volplugin/vendor/github.com/codegangsta/cli".Command) as type "github.com/codegangsta/cli".Commands in field value
```

> I think the end-user will want this tool,

I agree with the answer to the longer question :) ... if we can keep contivctl to be a minimal maintenance project, it is indeed a big value add.

**Comment by erikh** [comment]
rewrote contivctl, this can be closed.
