### ISSUE TITLE
Compatibility checks for backends

### ISSUE THREAD

**Issue by mapuri** [contiv/volplugin#237]
#231 provides user a way to specify the different backends to perform volplugin operations viz. CRUD, mount and snapshots.

This issue tracks the discussion about handling multiple backends at policy definition time (https://github.com/contiv/volplugin/pull/231#issuecomment-211478222)

Following are a few thoughts on possible ways of handling/providing mix of backends:

### Validate user input

This extends the way of policy definition as as introduced by #231. In this mode we let user specify the different backends and then we shall validate the user input against a compatibility matrix of supported backends.
**Pros**:
- let's user choose the backends of their choice as long as they are compatible 
- can be very useful to mix and match compatibile driver, assuming multiple such backends exist 

**Cons**:
- user needs to explicitly specify each backend to be able to avail behavior. For instance, user will need to explicitly specify snapshot driver to be able to take advantage of a backend's snapshot capability
- a complex compatibility matrix can exist, assuming we have multiple backends that can be compatible with each other.

### Derive compatible backends
In this mode we can accept just one backend name from the user at policy definition time i.e. keep the behavior as it was before #231. And then we initialize the different backends based on the user specified backend. For instance, when user specifies `ceph` then we shall initialize all 3 backends to be ceph, but when user specifies `nfs` we may only initialize `mount` backend and leave rest as empty

**Pros**
- simple compatibility checks
- frees user of having to understand compatibility of different backends. They still need to understand capabilities of each backend, which is simpler

**Cons**
- lacks the rick mix and match of different compatible backends

**Comment by erikh** [comment]
ok I think I know how this should be done.

* [ ] Design a schema system for backend drivers and their relationships to the following storage concepts (in `storage/driver.go`):
  * Volume
  * DriverOptions
  * these are the big two, but do perform diligence here so we cover all the bases
  * I think this will be a semi-large project by itself, please produce a design that works for you.
* [ ] Write schemas for each driver on each backend.
* [ ] Condense driver types to one backend call (`NewDriver`).
* [ ] Ensure volume and driveroptions get validated at processing time (see `Validate()` in `storage/driver.go`), and raise appropriate errors.
* [ ] Ensure policies in `systemtests/testdata` are updated with this behavior applied.
