### ISSUE TITLE
running volplugin in ubuntu 14.04

### ISSUE THREAD

**Issue by thbeh** [contiv/volplugin#245]
I am trying to setup volplugin to run on ubun 14.04 which will use a ceph deployed on docker. I am not sure how this is setup. I managed to install volmaster, volsupervisor and volcli.

running volmaster , i got this -
ERRO[0000] Could not retrieve global configuration: 100: Key not found (/volplugin/global-config) 

did I missed anything?

**Comment by jainvipin** [comment]
Did you try configuring global information, using step 3 at http://docs.contiv.io?

Following link specifies how the global configuration could look like:
https://github.com/contiv/volplugin/blob/master/systemtests/testdata/test/global1.json

**Comment by erikh** [comment]
Hi! So, a couple of quick things first: 

we have documentation here: http://contiv.github.io/docs/2_volplugin.html#Architecture if you haven't seen it yet. The top-level documentation is at http://contiv.github.io.

To answer your direct question, global configurations are not required (they have defaults) but to upload one, `volcli global upload < path/to/global.json` to upload a global policy. You can get an example one here: https://github.com/contiv/volplugin/blob/master/systemtests/testdata/ceph/global1.json

**Comment by erikh** [comment]
Global configurations are also covered here but only briefly: http://contiv.github.io/docs/2_volplugin.html#Configuration

Right below that is the policy JSON examples and you will likely want to read those as well.

**Comment by thbeh** [comment]
So that was what I have missed - global policy
now running docker volume create -

volplugin thbeh ~$ ./bin/volcli policy upload policy1 < systemtests/testdata/ceph/policy1.json
volplugin thbeh ~$ docker volume create -d volplugin policy1/test
docker: "volume create" requires 0 arguments.
See 'docker volume create --help'.

Usage:	docker volume create [OPTIONS]

Create a volume

**Comment by erikh** [comment]
This is docker's command-line tooling suffering a bit. It requires a `--name` option be passed for the volume name.

`docker volume create -d volplugin --name policy1/test`

Is it in the docs the other way? I'll verify but if you can point it out, that'd be great.

**Comment by erikh** [comment]
ah, it does! crap.

**Comment by thbeh** [comment]
The docker doc does but not contiv docs....that's for the help....

**Comment by erikh** [comment]
Yep! I'm going to close this now, but please feel free to start a new ticket if you run into trouble.

**Comment by erikh** [comment]
actually gonna leave this open until I fix the docs

**Comment by thbeh** [comment]
One last question though, does all the volmaster, volsupervisor and volplugin have to be run by sudo?

**Comment by erikh** [comment]
yes, they need to run as root. I'm working on a fully containerized solution (complete with a container to install it all) that should be available in the next week or two.

**Comment by erikh** [comment]
some additional notes:

volplugin and volmaster and volsupervisor all execute the `rbd` command heavily. volplugin mounts directories so it'll probably always need to be root. However, if you made volmaster and volsupervisor capable of running `rbd` without root access, you should be able to make those work without root.

Our NFS support should not need this, if you're interested in that. Just volplugin would need to be made root.

**Comment by erikh** [comment]
Docs are updated so this was closed. Please feel free to open additional tickets for more questions.
