### ISSUE TITLE
using volplugin in mesos

### ISSUE THREAD

**Issue by thbeh** [contiv/volplugin#246]
Got it to work with docker, thanks to erikh. Could the driver be use with mesos? How would json file looks like with marathon?

**Comment by erikh** [comment]
Not quite yet. We're looking at Mesos and Nomad as a target later this 
year.

Let's leave this open to track it.

-Erik

**Comment by thbeh** [comment]
Just an unintelligent question, maybe due to my inexperience on both volplugin and mesos. Mesos does creates docker containers but why couldn't Mesos uses the same -v argument to determine the volume?

**Comment by erikh** [comment]
It's definitely possible that's the case, but I don't really know mesos 
yet so I can't confirm. If you have the opportunity to test it, I'd love 
to hear your results.

-Erik

**Comment by thbeh** [comment]
Looks like it is working.....

**Comment by erikh** [comment]
whoa. NICE!

**Comment by thbeh** [comment]
Next to test is cassandra cluster on Mesos using volplugin on Ceph. For now I will close this. Thanks
