### ISSUE TITLE
dump etcd into a debug-friendly format when requested

### ISSUE THREAD

**Issue by erikh** [contiv/volplugin#247]
/cc @jainvipin 

This should have the following changes:

* [x] Respond to SIGUSR2
* [x] Dump etcd keys into /tmp (use mkstemp please)
* [x] tar.gz etcd keys and log filename in volplugin.

**Comment by erikh** [comment]
@unclejack since you are working on other things I'd like to give this ticket to @dseevr who offered to work on it.

**Comment by unclejack** [comment]
@erikh Sure!

**Comment by dseevr** [comment]
This can be closed now 👍
