### ISSUE TITLE
starting volplugin as service -- init.d scripts

### ISSUE THREAD

**Issue by thbeh** [contiv/volplugin#249]
Hi, I was wondering whether it is possible to start the 3 process (volmaster, volsupervisor and volplugin) as ubuntu/upstart (i am using trusty as my platform) services. Any idea how it can be done?

**Comment by erikh** [comment]
Sure! So, all the services run in foreground processes so they would need to be flagged as daemons in upstart init files or run as sysv rc scripts with debian's `start-stop-daemon` command. The latter is probably the path of least resistance.

I can try putting something together, but just about any existing init script in `/etc/init.d` will work as a good template if you need to get going before I can get to this.

Please leave this ticket open so we can address it.

**Comment by erikh** [comment]
Let's have this cover the appropriate ansible as well.

**Comment by tsaridas** [comment]
Maybe you can also have a package at https://launchpad.net/ubuntu/+ppas

**Comment by erikh** [comment]
SGTM; I'll need to learn how to do this, but soon, I promise. :)
