### ISSUE TITLE
Policy audit-logging / journal

### ISSUE THREAD

**Issue by erikh** [contiv/volplugin#269]
Policies cover volumes over time and may be modified, so the policy may drift over time (and the volumes themselves) so far that the volumes no longer resemble the policies they were created under

It would be nice to cross-reference these somehow, but for now a timestamped journal would be ideal. This would also be very useful for audit logging later.

I'm not sure if this information should live in etcd or be dumped elsewhere. I think that merits a conversation.

**Comment by erikh** [comment]
What I think should happen here (ideally in order) is:

* [ ] Policies copied on write to archive
* [ ] volcli command to retrieve them
* [ ] volcli command to watch them as they come in

Data structure wise:

What I think is best is to tree this off the root of volplugin: e.g., `/volplugin/policy-archive`. You can modify the constants and constructor in `config/config.go`, then you will create a new file say `config/archive.go` where you will place any code that relates to archiving, such as a path management tool (see `volume.go`, `policy.go`, etc.).

Each item should have a timestamp associated with it. If you want to order them some other way and encapsulate the policy in a struct that carries timestamp metadata -- or just encode it into the file -- up to you. There are problems with both approaches re: collisions I think.

So, rounding this out we'll see files like `/volplugin/policy-archive/policy1/test/100000000100101010` (assuming epoch or a sequence is used) which contain either the policy or a wrapped form.

The watch tool will just watch for incoming changes to `/volplugin/policy-archive` and print the results. That way it can be used as a pipe leader for say offline backups.

I think this covers what I require of the system; please let me know if something is unclear.

**Comment by dseevr** [comment]
What kind of output would you expect from `volcli volume policy-history foo/bar` (or whatever it ends up being called)?  A JSON array of objects with timestamp/policy text?

```json
{
	"policy-history": [
		{
			"uploaded_at": 123456789,
			"active": true,
			"policy": "the raw policy data as it was uploaded as a string"
		},
		{
			"uploaded_at": 123456780,
			"active": false,
			"policy": "..."
		},
		// ...
	]
}
```

We could include the active policy, omit it, or include it and have an "active" key like in the example above.  Should each history entry in the response include the associated policy as a raw string, as a regular JSON object, or both?

**Comment by erikh** [comment]
I think `volcli policy history list foo` (plaintext list) and `volcli policy history get foo <timestamp>` (json payload) would be better. What do you think?

**Comment by dseevr** [comment]
What are you thinking the plaintext listing would look like?  CSV? Human-readable?

**Comment by erikh** [comment]
just line by line, something that can be processed trivially with `awk` or `cut`. look at `volume list` and `policy list` for examples.
