### ISSUE TITLE
improve testing

### ISSUE THREAD

**Issue by unclejack** [contiv/volplugin#271]
This is a sort of a catch all issue for some improvements we can make to catch some errors sooner.

- [ ] add more tests which shell out to volcli to validate output
- [ ] add more system tests to run before the longer running ones
- [ ] maybe bail out if the short tests fail to avoid running the long running ones

**Comment by erikh** [comment]
can you clarify what you mean by testing here?

**Comment by unclejack** [comment]
@erikh It's done. I'll add more items as I think of more things to test.

**Comment by erikh** [comment]
I don't agree with "maybe bail out". I want all the test data, so I can make an informed decision. Please do not attempt this.

**Comment by erikh** [comment]
I'm also unsure what short system test ordering would accomplish given the previous request. I thoroughly love the volcli testing.

**Comment by erikh** [comment]
sgtm
