### ISSUE TITLE
Error while copying snapshot to a volume

### ISSUE THREAD

**Issue by vishal-j** [contiv/volplugin#294]
I see below error while calling this rest endpoint
POST /volumes/copy

Supplied json
{
  "volume": "postgres-vol",
  "policy": "db-storage-policy",
  "Options": {
       "target": "volumefromSnapshot",
	   "snapshot": "2016-06-03-15:00:00.573457352-+0000-UTC"
	}
}
Publishing Volume: Creating new volume "volumefromSnapshot" from volume "db-storage-policy/postgres-vol", snapshot "2016-06-03-15:00:00.573457352-+0000-UTC": Locking Operation Failed
	github.com/contiv/volplugin/errors.init [errors.go 49]
	github.com/contiv/volplugin/config.init [volume.go 467]
	main.init [cli.go 61]
	runtime.main [proc.go 177]
	runtime.goexit [asm_amd64.s 1998]
	github.com/contiv/volplugin/volmaster.(*DaemonConfig).handleCopy [daemon.go 484]
	github.com/contiv/volplugin/volmaster.(*DaemonConfig).(github.com/contiv/volplugin/volmaster.handleCopy)-fm [daemon.go 79]
	github.com/contiv/volplugin/volmaster.logHandler.func1 [daemon.go 154]
	net/http.HandlerFunc.ServeHTTP [server.go 1618]
	github.com/contiv/volplugin/vendor/github.com/gorilla/mux.(*Router).ServeHTTP [mux.go 98]
	net/http.serverHandler.ServeHTTP [server.go 2081]
	net/http.(*conn).serve [server.go 1472]
	runtime.goexit [asm_amd64.s 1998]
	github.com/contiv/volplugin/errors.init [errors.go 12]
	github.com/contiv/volplugin/config.init [volume.go 467]
	main.init [cli.go 61]
	runtime.main [proc.go 177]
	runtime.goexit [asm_amd64.s 1998]

This is what my policy looks like:
{"name":"db-storage-policy","create":{"size":"30MB","filesystem":"ext4"},"runtime":{"snapshots":true,"snapshot":{"frequency":"90m","keep":30},"rate-limit":{"write-iops":1000,"read-iops":1000,"write-bps":100000000,"read-bps":100000000}},"driver":{"pool":"rbd"},"filesystems":{"btrfs":"mkfs.btrfs %","ext4":"mkfs.ext4 -m0 %","falsefs":"/bin/false"},"backends":{"crud":"ceph","mount":"ceph","snapshot":"ceph"}}

**Comment by erikh** [comment]
I think I see the issue here. Was the volume mounted at the time you took the snapshot?

**Comment by erikh** [comment]
At the time you made the COPY, rather. The snapshots should be working fine.

**Comment by vishal-j** [comment]
Yes, the volume postgres-vol was mounted when I made the copy.
