### ISSUE TITLE
API change requests for UX improvements

### ISSUE THREAD

**Issue by erikh** [contiv/volplugin#298]
@vishal-j sent us these requests via email: 

* Accept a Request to copy a snapshot of an existing volume to a new volume.
  * POST /volumes/copy

```json
{
  "volume": "oldvolume",
  "policy": "policy",
  "options": {
    "target": "newvolume",
    "snapshot": "snapshotname"
  }
} 
```

* Returns the mount for the specified volume with the specified policy.
  * GET /uses/mounts/{policies}/{volume}
    * {policy} is the name of the policy
    * {volume} is the name of the volume

```json
{
  "volume": "test1/bar",
  "hostname": "mon0",
  "reason": "Mount"
}
```

**Comment by unclejack** [comment]
Isn't the second part already taken care of by https://github.com/contiv/volplugin/blob/master/volmaster/daemon.go#L107 ?

**Comment by erikh** [comment]
#298 resolves the first one, the others are vetted
