### ISSUE TITLE
New flags/functionality for `volcli volume remove`

### ISSUE THREAD

**Issue by erikh** [contiv/volplugin#307]
After discussing a few UX details with @vvb I think this is the best way to move forward with this command:

* `-r`: retry -- this is the current "wait until lock remove or timeout" behavior.
* `-f`: force -- this trumps all locks and removes the volume forcefully if possible. The ultra-destructive version of `volcli volume force-remove`.
* default: attempt to acquire lock and abort immediately if failed.

Please let me know if you have different ideas on how this should work.

/cc @vvb @jainvipin @mapuri @unclejack @dseevr

**Comment by vvb** [comment]
@erikh LGTM, as stated by you already - aborting immediately needs to be the default option for better UX, while still providing users the options for other behaviours.

**Comment by unclejack** [comment]
@erikh Would you like to have `force-remove` moved to a flag? I've looked at the code and I think it'd be worth discussing the changes in slightly more detail.

**Comment by erikh** [comment]
no.

**Comment by erikh** [comment]
fixed by #311
