### ISSUE TITLE
[documentation] link to example global configs is wrong in getting started guide

### ISSUE THREAD

**Issue by zachwalton** [contiv/volplugin#314]
http://docs.contiv.io/2_volplugin.html#Do it yourself

"Upload a global configuration. You can find an example one here"

This is a 404: https://github.com/contiv/volplugin/blob/master/systemtests/testdata/global1.json

Should point to:

https://github.com/contiv/volplugin/blob/master/systemtests/testdata/globals/global1.json

**Comment by erikh** [comment]
Well that's embarrassing. :) I'll try to fix it tonight, thanks for the report!

**Comment by erikh** [comment]
https://raw.githubusercontent.com/contiv/volplugin/master/systemtests/testdata/globals/global1.json here is where you want to go.

**Comment by zachwalton** [comment]
Rather than open a flurry of documentation bugs...

```
docker volume create -d volplugin \
  --name policy2/image \
  --opt size=1000
```

This should actually be:

```
docker volume create -d volplugin \
  --name policy2/image \
  --opt size=1000MB
```

(1000MB vs. 1000)

Got everything working, thanks! 👏🏻

**Comment by erikh** [comment]
hahaha. thanks! appreciated.

**Comment by erikh** [comment]
@shaleman can you make these changes when you integrate our new documentation site?

**Comment by erikh** [comment]
The reason I'm asking is that they're small and I'd have to re-split hte source material up.

**Comment by shaleman** [comment]
done.

**Comment by erikh** [comment]
Thanks!!! I'm going to close this now.
