### ISSUE TITLE
'publishuse' runs indefinitely due to mount failure

### ISSUE THREAD

**Issue by yuva29** [contiv/volplugin#324]
Steps to reproduce
1. create a volume using NFS policy which empty backend attribute
2. try to mount the volume in container (mount should fail)
3. check volplugin log

Log here: https://gist.github.com/3be2c6dbb67afc707a814de55f304483

**Comment by erikh** [comment]
this is not caused by a policy backend that is left blank, but a missing mount option.

we should add tests for both, though, as I don't think the first case exists either.
