### ISSUE TITLE
tests with heisenbugs

### ISSUE THREAD

**Issue by erikh** [contiv/volplugin#358]
Going to keep a running list of these as I encounter them in CI. Please take one or two if you get time.

* [ ] `systemtestSuite.TestVolsupervisorRestart`
* [ ] `systemtestSuite.TestBatteryParallelMount` (nfs only)

**Comment by yuva29** [comment]
- [ ] `systemtestSuite.TestBatteryMultiMountSameHost `

**Comment by erikh** [comment]
I think I fixed the multi mount problems in #374, can you review again when merged?

**Comment by erikh** [comment]
these tests have been resolved.
