### ISSUE TITLE
[volsupervisor] rbd clone invocation incorrect for non-default pools

### ISSUE THREAD

**Issue by zachwalton** [contiv/volplugin#362]
ceph version: 0.94.6
volplugin version: 0.20.0

with a pool named "example", the following invocation of volcli:

```
$ volcli  volume snapshot copy policy1/volume1 2016-07-22-22:30:00.76904695-+0000-UTC  volume1-clone1
```

invokes:

```
$ rbd clone policy1.volume1 policy1.volume1-clone1 --snap 2016-07-22-22:30:00.76904695-+0000-UTC --pool example
rbd: error opening pool rbd: (2) No such file or directory
```

this results in a  500 error from the API server and the clone isn't created.  the correct rbd invocation is:

```
rbd clone example/policy1.volume1 example/policy1.volume1-clone1 --snap 2016-07-22-22:30:00.76904695-+0000-UTC
```

the first `example/` is the source pool and the second is the destination pool. the `--pool` flag isn't necessary.

**Comment by erikh** [comment]
oh interesting! I guess I missed this in my tests. Thanks for the report, I'll investigate it this week.

**Comment by erikh** [comment]
Zach,

#369 should resolve this. It will likely drop in 0.3, probably in a few weeks.

**Comment by zachwalton** [comment]
excellent, thank you! 👏🏻
