### ISSUE TITLE
backend.NewDriver needs some TLC

### ISSUE THREAD

**Issue by erikh** [contiv/volplugin#382]
This call takes a lot of differing arguments that change the behavior of it dramatically.

Suggestion: use a struct as the argument, which essentially gives us named parameters (that we can choose to ignore).

Either way this is going to require a fair bit of cleanup in the `api/` module alongside it.

**Comment by yuva29** [comment]
https://github.com/contiv/volplugin/blob/master/storage/backend/backends.go#L70 

We can handle this 2 ways:
1. Define a struct with all the required args for `NewDriver()`
```
type NewDriverRequest {
backend string
driverType string
do *storage.DriverOptions
mountPath string // only used during "MountDriver" creation.
}
```

2. Define a map with all required attributes
```
map[string]string {"backend": "ceph", "driverType": "mount", etc..}
```
I would prefer Option 1 because its less error prone.

Let me know your thoughts.

**Comment by erikh** [comment]
What are the driver options needed for here again?

-Erik

**Comment by yuva29** [comment]
its for the validation. https://github.com/contiv/volplugin/blob/master/storage/backend/backends.go#L76

If we let the caller handle it, then we have return interface.

**Comment by erikh** [comment]
Let's make this look like so:

```go
NewDriver(backend string, backends *BackendOptions)
```

Write a `Validate` for BackendOptions and call that in your construction code.

Any reason this wouldn't work?

**Comment by yuva29** [comment]
@erikh what do you expect it to return ?

And I suppose the already existing `*BackendDrivers` would work. Just in case you meant a different  `BackendOptions`

**Comment by erikh** [comment]
It should return a driver as it currently does?

**Comment by yuva29** [comment]
Right now, it just return an error. But with the new changes, it should return a driver which can be of MountDriver, SnapshotDirver or MountDriver. how about an interface?

**Comment by erikh** [comment]
yeah, rename NewDriver to validate().

**Comment by erikh** [comment]
leave the rest alone please.

**Comment by erikh** [comment]
well, do remove the driver options. Just validate the backend (string) and backend driver map (struct)

**Comment by yuva29** [comment]
If all we do is Validation around backends, then I guess it is better to revert to how it was so that the driver options will also be taken into account.

```
func (cfg *Volume) validateBackends() error {		
 -	// We use a few dummy variables to ensure that global configuration is		
 -	// not needed in the storage drivers, that the validation does not fail		
 -	// because of it.		
 -	do, err := cfg.ToDriverOptions(time.Second)		
 -	if err != nil {		
 -		return err		
 -	}		
 -		
 -	if cfg.Backends.CRUD != "" {		
 -		crud, err := backend.NewCRUDDriver(cfg.Backends.CRUD)		
 -		if err != nil {		
 -			return err		
 -		}		
 -		
 -		if err := crud.Validate(do); err != nil {		
 -			return err		
 -		}		
 -	}		
 -		
 -	mnt, err := backend.NewMountDriver(cfg.Backends.Mount, "/mnt")		
 -	if err != nil {		
 -		return err		
 -	}		
 -		
 -	if err := mnt.Validate(do); err != nil {		
 -		return err		
 -	}
-	if cfg.Backends.Snapshot != "" {		
 -		snapshot, err := backend.NewSnapshotDriver(cfg.Backends.Snapshot)		
 -		if err != nil {		
 -			return err		
 -		}		
 -		if err := snapshot.Validate(do); err != nil {		
 -			return err		
 -		}		
 -	}		
 -		
 -	return nil
}
```

Also, backends data validation is handled here https://github.com/yuva29/volplugin/blob/cb52b08d68ef5e19e9cd886b335f4607f3bab439/config/schema.go#L61-L69 

LMKWYT

**Comment by yuva29** [comment]
@erikh Let me know your thoughts on this

**Comment by erikh** [comment]
Yeah that seems correct. Not sure how we got our wires crossed here but this is the correct behavior.
