### ISSUE TITLE
building & running checks without Vagrant

### ISSUE THREAD

**Issue by unclejack** [contiv/volplugin#395]
Volplugin relies a lot on the vagrant environment to build and to do many other things.

Perhaps it would be a good idea to make it possible to build in Docker in a very similar way. This would make it possible to build volplugin where VMs can't be brought up for various reasons.

**Comment by erikh** [comment]
https://github.com/ceph/ceph-docker/issues/330 this won't work.

Please check the closed issues. I'm pretty sure I already detailed this pretty heavily.

**Comment by unclejack** [comment]
This was only about building the volplugin binaries and running the check scripts.
