### ISSUE TITLE
Volsupervisor should only snapshot when the volume is in use

### ISSUE THREAD

**Issue by erikh** [contiv/volplugin#396]
We currently create the snapshot either way, I don't think pruned snaps of the same volume every 10m (for example) when the data is at rest leads to very useful snapshot logs.

**Comment by yuva29** [comment]
```go
if !vol.unlocked {
  if _, err:= c.etcdClient.Get(context.Background(), prefixed(rootUse, UseTypeMount, volName), nil); err == nil { //key found successfully
    takeSnapshot()
  }
} else { // No mount lock exists for them
// One option that I can think off now, Iterate over all the docker containers and check if the volume is being mounted there or not; and act accordingly.
}
```

and all the changes goes here https://github.com/contiv/volplugin/blob/master/volsupervisor/loop.go#L136

**Comment by erikh** [comment]
snap unlocked mode containers as they do now, no point in making this super complicated yet.

The rest seems like what I was thinking.
