### ISSUE TITLE
Backend support for Consul

### ISSUE THREAD

**Issue by ChristianKniep** [contiv/volplugin#59]
Hey there,

I am carefully crawl towards CEPH backed volumes after I played around with the new networking:
http://qnib.org/2015/11/29/multi-host-slurm/

I would like to expand the post with ceph-backed volumes. For now you only support `etcd` if I get the `config/config.go` file right... Not [yet] a way to plug in `Consul`. No big deal, I could spin up an etcd-instance, no problem.

Just so that I know. Maybe others are interested in this as well.

Cheers, keep up the great work
Christian

**Comment by erikh** [comment]
OK, I'll look into it, but prioritizing it will be hard due to other features that need to be developed. If you would be interested, I can guide you through what you need to do to implement this patch.

**Comment by ChristianKniep** [comment]
Could look into it. Not sure if I got the time, but I'll try. First I am going to check it out using `etcd`.
Do you want to keep the issue open to track the matter or should I close it?

**Comment by erikh** [comment]
Leave it open, please. If you irc at all, I'm `erikh` there as well. Feel free to message me.

**Comment by erikh** [comment]
FWIW, the major area that would need work is in the `config/` directory, most of the etcd operations happen there. Beyond that, it's modifying the interface a little bit to accommodate multiple backends.

**Comment by erikh** [comment]
hi @ChristianKniep, while we may consider this in the future, I don't believe it's realistic to keep this ticket open in the meantime, as we have no definite plans to implement it.

I'm going to close this but we will consider the feature in the future. Thanks for submitting the idea.
