### ISSUE TITLE
requestVolumeConfig with tenant/volume or tenant/name?

### ISSUE THREAD

**Issue by bnoon** [contiv/volplugin#60]
I am just testing this out and I get an error when creating a volume and attempting to mount it into a container.

Here are some logs from volplugin:
```
time="2015-11-30T19:15:48Z" level=debug msg="Dispatching Path with {\"Name\":\"tenant1/foo\"}" 
time="2015-11-30T19:15:48Z" level=info msg="Returning mount path to docker for volume: \"tenant1/foo\"" 
time="2015-11-30T19:15:48Z" level=warning msg="Returning HTTP error handling plugin negotiation: Requesting tenant configuration Status was not 200: was 404: \"\"" 
time="2015-11-30T19:15:48Z" level=debug msg="Dispatching Mount with {\"Name\":\"tenant1/foo\"}" 
time="2015-11-30T19:15:48Z" level=info msg="Mounting volume \"tenant1/foo\"" 
time="2015-11-30T19:15:48Z" level=warning msg="Returning HTTP error handling plugin negotiation: Could not determine tenant configuration Status was not 200: was 404: \"\"" 
```

The logs from volmaster shows that the it get the requests:
```
time="2015-11-30T19:15:48Z" level=debug msg="Dispatching /request with {\"volume\":\"tenant1/foo\",\"tenant\":\"tenant1\"}" 
time="2015-11-30T19:15:48Z" level=debug msg="Dispatching /request with {\"volume\":\"foo\",\"tenant\":\"tenant1\"}" 
```
but the `volume` is different.

should https://github.com/contiv/volplugin/blob/master/volplugin/handlers.go#L132

be `volConfig, err := requestVolumeConfig(master, uc.Tenant, uc.Name)`?

**Comment by erikh** [comment]
Interesting, can you give me the command you ran for `docker volume create` and `docker run` ?

**Comment by bnoon** [comment]
Sure.
```
docker volume create -d volplugin --name=tenant1/foo
docker run -it -v tenant1/foo:/mnt ubuntu bash
```
I had uploaded the canned `systemtests/testdata/intent1.json` file for tenant1.

I am running this against an existing ceph cluster with ceph running in containers.

**Comment by erikh** [comment]
Ok. Can you `rbd ls rbd` for me and see if you get a volume named `tenant1.foo`? Also, if you could upload the output of `etcdctl ls --recursive /volplugin` that would be immensely useful.

Thank you very much for helping me debug this!

**Comment by bnoon** [comment]
`rbd ls rbd` lists `foo` but not `tenant1.foo`.  

Should I have named the volume with the tenant?

`etcdctl ls --recursive /volplugin` shows:
```
/volplugin/users
/volplugin/users/tenant1
/volplugin/tenants
/volplugin/tenants/tenant1
/volplugin/volumes
/volplugin/volumes/tenant1
```

**Comment by erikh** [comment]
No, this should not be necessary.

It looks like the volume isn't getting registered in etcd. I'll see if I can recreate this. Are you using a recent build?

**Comment by erikh** [comment]
Oh, did you create the volume yourself?

**Comment by bnoon** [comment]
I am using the 11/29 release.  I created the ceph volume myself since I want to mount existing volumes into containers.

Is the call to `requestVolumeConfig(master, "tenant1","tenant1/foo")` correct (line 132 volplugin/handlers.go)?

**Comment by erikh** [comment]
Yes, this code is correct. I see the problem now.

Unfortunately volplugin is not currently capable of managing existing rbd volumes. When you `docker volume create` for the first time for a given volume name, its existence is registered in etcd.

Now, there are patches in progress that resolve some of this, I will leave this open and ping here when these patches are ready. For now, though, you must manage your volumes through volplugin.

Very sorry about the inconvenience.

**Comment by bnoon** [comment]
Ok. Thanks.

As an additional point, I tried to `docker volume create -d volplugin --name=tenant1/test` and got the following:

```
Error response from daemon: Plugin Error: VolumeDriver.Create, {"Mountpoint":"","Err":"Could not determine tenant configuration Status was not 200: was 500: \"Creating volume Error creating filesystem on /dev/rbd1 with cmd: \\\"mkfs.ext4 -m0 %\\\". Error: exit status 1\""}
```

**Comment by erikh** [comment]
Are you running volplugin as root?

**Comment by erikh** [comment]
and volmaster, sorry

**Comment by bnoon** [comment]
They are both running in `--privileged` containers.  I can `exec` in the volplugin container to create and mount rbd devices.  When the above fails, there is a /dev/rbd1 device left in the container and on the host.  From in the container I am able to `mkfs.ext4 /dev/rbd1` and mount it up.

**Comment by bnoon** [comment]
I start the containers as follows
```
docker run -d --name volmaster \
  --net=host --privileged \
  -e KV_IP=10.1.0.11 \
  vol \
  volmaster --debug --listen 10.1.0.11:9005 --etcd http://10.1.0.11:2379

docker run -d --name volsuper \
  --net=host --privileged \
  -e KV_IP=10.1.0.11 \
  vol \
  volsupervisor --etcd http://10.1.0.11:2379


docker run -d --name volplug \
  --net=host --privileged \
  -v /var/run/docker:/var/run/docker \
  -v /sys:/sys -v /dev:/dev \
  -e KV_IP=10.1.0.11 \
  volplug \
  volplugin --debug --master 10.1.0.11:9005
```

**Comment by erikh** [comment]
Can you try running it outside of containers first? I haven't fully vetted this yet.

**Comment by erikh** [comment]
Ok, I'm going to experiment a bit, I think your hunch on the code is right on a second pass. Sorry if I took too much of your time, I will let you know in a bit.

**Comment by erikh** [comment]
OK, so I have fixed the code in a PR here, but I cannot recreate the getPath error you were seeing before; docker 1.9.0 skips over the pathing issue and happily continues, I don't quite understand yet why you are seeing this.

PR is here: https://github.com/contiv/volplugin/pull/62

**Comment by bnoon** [comment]
I think PR #62 fixes this issue for me (btw, I am running docker 1.9.1 if that matters) so I am closing this issue.

I am still unable to get ceph volumes to mount via the docker plugin, but that is probably due to my running ceph and volplugin in containers.

I will file I different issue on that.
