### ISSUE TITLE
How is the container mount point propagated to docker daemon?

### ISSUE THREAD

**Issue by bnoon** [contiv/volplugin#63]
This is more of an observation than an issue, so feel free to close it.

I am trying to run the volplugin daemons in containers on a system that has ceph installed in containers.

I am sure I am missing something, but I thought that docker plugins were designed to be able to run as in containers.  So this is an experiment.

I run some containers as follows:
```
docker run -d --name volmaster \
 --net=host --privileged -e KV_IP=10.1.0.11 \
 vol \
 volmaster --debug --listen 10.1.0.11:9005 --etcd http://10.1.0.11:2379

docker run -d --name volsuper \
 --net=host --privileged -e KV_IP=10.1.0.11 \
 vol \
 volsupervisor --etcd http://10.1.0.11:2379

docker run -d --name volplug \
 --net=host --privileged -e KV_IP=10.1.0.11 \
 -v /var/run/docker:/var/run/docker \
 -v /sys:/sys -v /dev:/dev \
 volplug \
 volplugin --debug --master 10.1.0.11:9005
```

In the volplug container I can list my rbd images and map/unmap them fine with `rbd` commands.

`docker volume create -d volplugin --name=tenant1/test` works fine.

However `docker run -it --rm -v tenant1/test:/mnt ubuntu bash` will generate an error from docker:
```
Timestamp: 2015-12-01 16:14:49.745337292 -0500 EST
Code: System error

Message: stat /mnt/ceph/rbd/tenant1.test: no such file or directory

Frames:
---
0: setupRootfs
Package: github.com/opencontainers/runc/libcontainer
File: rootfs_linux.go@40
---
1: Init
Package: github.com/opencontainers/runc/libcontainer.(*linuxStandardInit)
File: standard_init_linux.go@57
---
2: StartInitialization
Package: github.com/opencontainers/runc/libcontainer.(*LinuxFactory)
File: factory_linux.go@242
---
3: initializer
Package: github.com/docker/docker/daemon/execdriver/native
File: init.go@35
---
4: Init
Package: github.com/docker/docker/pkg/reexec
File: reexec.go@26
---
5: main
Package: main
File: docker.go@18
---
6: main
Package: runtime
File: proc.go@63
---
7: goexit
Package: runtime
File: asm_amd64.s@2232
Error response from daemon: Cannot start container 18abc76c63d7b2661b6423e553c5c03d03bca6874681cd1564fc225b7e3a923e: [8] System error: stat /mnt/ceph/rbd/tenant1.test: no such file or directory
```

I am guessing that I am not propagating the mounted filesystem correctly to the system docker.  I have put a check in the storage/ceph/ceph.go code and the filesystem is mounted and readable in the volplug container.  Everything then gets cleaned up after the error.

I have `MountFlags=slave` set for the docker daemon.

Should I share the mount point `/mnt/ceph`?

**Comment by erikh** [comment]
yeah, that's probably necessary. /mnt/ceph is where all the mountpoints 
for the ceph volumes are created.

I'm probably going to document your successes/failures on this in our 
documentation, so any context you can share during your experimentations 
is certainly useful!

-Erik
